name: "Post to Bluesky"

on:
    schedule:
      - cron: "0 0,4,8,12,16,20 * * *"
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: ".nvmrc"
      - run: npm ci
      - name: Send post
        run: node bluesky.js
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      - name: Commit array file
        run: |
          git config --global user.name 'RebeccaAnne'
          git config --global user.email 'RebeccaAnne@users.noreply.github.com'
          git add arrays-bluesky.json
          git commit -m "Bluesky Array Update"
          git push